name: Build Beta
on:
  workflow_dispatch:

jobs:
  IOS:
    name: IOS
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install sponge
        run: brew install sponge
      - name: Setup
        uses: ./.github/actions/setup
        with:
          platform: "ios"
      - name: Build Packages
        run: |
          cd ios
          xcodebuild -scheme LxMusicMobile -workspace LxMusicMobile.xcodeproj -configuration release archive -archivePath LxMusicMobile.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
          chmod a+x ../scripts/xcarchive_to_ipa.sh
          ../scripts/xcarchive_to_ipa.sh LxMusicMobile.xcarchive
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: app-release.ipa
          path: ios/*.ipa


  Android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Setup Env
        uses: ./.github/actions/setup

      - name: Build Packages
        shell: bash
        run: |
          cd android
          ./gradlew assembleRelease
          rm -f app/${{ secrets.KEYSTORE_STORE_FILE }}

      # Push tag to GitHub if package.json version's tag is not tagged
      - name: Get package version
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV

      - name: Generate file MD5
        run: |
          cd android/app/build/outputs/apk/release
          md5sum *.apk

      - name: Upload Artifact
        uses: ./.github/actions/upload-artifact
        env:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
